name: PR Merge Dev NPM Preview

on:
  pull_request_target:
    types: [closed]
    paths: 
      - "packages/cherry-markdown/**"

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  dev-deploy:
    if: github.repository == 'Tencent/cherry-markdown' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Merge Commit SHA
        run: echo "COMMIT_SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y moreutils

      - name: Update package.json
        working-directory: ./packages/cherry-markdown
        run: |
          BASE_VERSION=$(jq -r .version package.json)
          VERSION="${BASE_VERSION}-dev.${{ env.COMMIT_SHORT_SHA }}"
          jq --arg name "@cherry-markdown/cherry-markdown-dev" \
             --arg version "$VERSION" \
             '.name = $name | .version = $version | del(.scripts.publish?)' package.json | sponge package.json
          echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
          echo "PACKAGE_NAME=@cherry-markdown/cherry-markdown-dev" >> $GITHUB_ENV

      - name: Update README
        run: |
            cat <<-EOF > README.md
              <!-- DEV PREVIEW WARNING -->
                <div align="center">
                  <div style="padding: 16px; background: #fff3d8; border-radius: 8px; margin: 20px 0;">
                     <strong>⚠️ 开发预览警告 / Development Preview Warning</strong>
                    <p>此版本为临时测试版（${PACKAGE_NAME}@${PACKAGE_VERSION}），禁止在生产环境使用！最后更新时间：$(date +'%Y-%m-%d %H:%M:%S')</p>
                    <p>This is a development preview version (${PACKAGE_NAME}@${PACKAGE_VERSION}), do NOT use in production! Last updated: $(date +'%Y-%m-%d %H:%M:%S')</p>
                  </div>
                </div>
              $(cat README.md)
            EOF

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: yarn

      - name: Install and build
        working-directory: ./packages/cherry-markdown
        run: yarn install && yarn build

      - name: Publish to NPM
        working-directory: ./packages/cherry-markdown
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Post comments
        uses: actions/github-script@v7
        with:
          script: |
            const { issueNumber, repo, owner } = context.issue();
            const comment = `Dev Preview Published!\nPackage: ${process.env.PACKAGE_NAME}@${process.env.PACKAGE_VERSION}\nNPM Link: https://npmjs.com/package/${process.env.PACKAGE_NAME}/v/${process.env.PACKAGE_VERSION}`;
            
            // 评论到PR
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });

            // 提取关联Issue（增强正则）
            const refIssues = [...(context.payload.pull_request.body || '').matchAll(/(?:#|https:\/\/github\.com\/Tencent\/cherry-markdown\/issues\/)(\d+)/g)]
              .map(m => m[1])
              .filter((v,i,a) => a.indexOf(v) === i); // 去重

            refIssues.forEach(issue => {
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issue,
                body: `关联PR #${context.payload.pull_request.number} 已发布测试版: ${comment}`
              });
            });