name: Release

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      publishedPackages: ${{ steps.changesets.outputs.publishedPackages }}
      publishedClientVersion: ${{ steps.extract_client_version.outputs.client_version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: |
          yarn
          yarn build

      - name: Publish VSCode Extension
        run: |
          cd packages/vscodePlugin
          jq '.name="cherry-markdown"' package.json > temp.json && mv temp.json package.json
          set npm_config_workspaces=false
          vsce package --no-yarn
       # vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
