name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Check for changesets
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          title: "chore: release"
          commit: "chore: release"
          publish: yarn changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print changesets outputs
        run: |
              echo "hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}"
              echo "published: ${{ steps.changesets.outputs.published }}"
              echo "releasedPackages: ${{ toJson(steps.changesets.outputs.publishedPackages) }}"
              echo "releasedPackages length: ${{ fromJson(steps.changesets.outputs.publishedPackages).length }}"
              
      - name: Publish
        if: ${{ contains(steps.changesets.outputs.publishedPackages, '"name":"cherry-markdown"') }}
        run: |
              echo "Publishing Cherry Markdown"
      #     yarn build
      #     cd packages/cherry-markdown
      #     npm publish --access public
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish VSCode Extension
        if: ${{ contains(steps.changesets.outputs.publishedPackages, '"name":"cherry-markdown-vscode-plugin-test"') }}
        run: |
            echo "Publishing VSCode Extension"
      #     npm install -g vsce
      #     yarn build
      #     cd packages/vscodePlugin
      #     vsce package
      #     vsce publish
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish Client
        # if: ${{ contains(steps.changesets.outputs.publishedPackages, '"name":"@cherry-markdown/client"') }}
        uses: ./.github/actions/build-client-release/action.yaml